version: "3.8"

services:
  flask:
    build: .
    #image: flask-img
    #container_name: flask-container
    ports:
      - 5000:5000
    volumes: 
      - .:/app
    links:
      - mongodb
    environment:
      FLASK_RUN_HOST: 0.0.0.0
    restart: always

  mongodb:
    image: mongodb/mongodb-community-server:latest
    #container_name: mongodb-container
    #hostname: 
    ports:
      - 27017:27017
    restart: always
